version: "3.9"

services:
  node1:
    build:
      context: .
      dockerfile: dockerfile-arm
    networks:
      - mycelnet
    ports:
      - "1317:1317"
      - "4500:4500"
      - "26657:26657"
    volumes:
      - "~/.mycel:/root/.mycel"
  node2:
    build:
      context: .
      dockerfile: dockerfile-arm
    networks:
      - mycelnet
    command: bash
    tty: true

networks:
  mycelnet:

