name: Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  GO_VERSION: "1.20.2"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 🐿 Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Display go version
        run: go version
      - name: 🧪 Test
        run: go test -v x/...
